# -*- coding: utf-8 -*-
"""HillsandValleys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b9RKJf8oxp9AcvADXbVH_eV7RUYRCOoX

HILL AND VALLEY PREDICTION USING LOGISTICS REGRESSION

IMPORT LIBRARY
"""

import pandas as pd

import numpy as np

"""IMPORT DATASET"""

df = pd.read_csv('https://raw.githubusercontent.com/Lorddhaval/Dataset/main/Hill%20Valley%20Dataset.csv')

df.head()

df.info()

df.describe()

df.columns

print(df.columns.tolist())

df.shape

df['Class'].value_counts()

df.groupby('Class').mean()

y = df['Class']

y.shape

y

X = df.drop('Class', axis=1)

X

"""Get Plot of First Two Rows"""

import matplotlib.pyplot as plt

plt.plot(X.iloc[0,:])
plt.title('Valley');

plt.plot(X.iloc[1,:])
plt.title('Hill');

"""Get X Variable Standardized"""

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

X = ss.fit_transform(X)

X

"""Get Train Test Split"""

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, stratify = y, random_state=222529)


X_train.shape, X_test.shape, y_train.shape, y_test.shape

"""Get Model Train"""

from sklearn.linear_model import LogisticRegression


lr = LogisticRegression()


lr.fit(X_train, y_train)

"""Get Model Prediction"""

y_pred = lr.predict(X_test)


y_pred.shape

y_pred

"""Get Probabilty of Each Predicted Class"""

lr.predict_proba(X_test)

"""Get Model Evaluation"""

from sklearn.metrics import confusion_matrix, classification_report


print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

"""Get Future Prediction"""

X_new = df.sample(1)

X_new

X_new = X_new.drop('Class', axis = 1)

X_new = ss.fit_transform(X_new)

y_pred_new = lr.predict(X_new)

lr.predict_proba(X_new)